name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  quality:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up uv with Python 3.11
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          activate-environment: true

      - name: Install build toolchain
        run: uv pip install build ninja cmake

      - name: Install project
        run: uv pip install -e .

      - name: Install pre-commit
        run: uv pip install pre-commit

      - name: Run pre-commit hooks (all files)
        run: uv run pre-commit run --all-files

  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: quality
    permissions:
      contents: write          # <- minimal fix: allow git-auto-commit-action to push
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up uv with Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true

      - name: Install build toolchain
        run: uv pip install build ninja cmake

      - name: Install project
        run: uv pip install -e .[dev]

      - name: Install test dependencies
        run: uv pip install pytest pytest-cov

      - name: Run pytest
        run: uv run pytest

      - name: Generate coverage badge
        if: matrix.python-version == '3.11'
        uses: tj-actions/coverage-badge-py@v2
        with:
          input: coverage.xml
          output: badges/coverage.svg

      - name: Upload coverage
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: coverage.xml
          retention-days: 7

      - name: Commit coverage badge
        if: matrix.python-version == '3.11' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update coverage badge [skip ci]"
          file_pattern: badges/coverage.svg
